# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 07:49
from __future__ import unicode_literals

import bookstoreapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=30)),
                ('title', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('language', models.CharField(default='en', max_length=3)),
                ('pub_date', models.DateField(default=None)),
                ('image_link', models.ImageField(blank=True, null=True, upload_to=bookstoreapp.models.__get_book_path__)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='unnamed-book', editable=False, max_length=75)),
            ],
        ),
    ]
